name: Publish

on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.12.0
      - run: devbox run -- bash -c 'cd pkg/emitters/websocket/static && bun install'
      - run: devbox run -- bash -c 'cd pkg/emitters/websocket/static && bun run build'
      - id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: devbox run -- just version="${{ env.VERSION }}" build-all
      - run: |
          cd dist
          sha256sum * > checksums.txt
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
